
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gate-library"
version = "0.1.0"

dynamic = [
  "description",
  "authors",
  "requires-python"
]
